# Generated by Django 3.1.4 on 2022-11-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20221103_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=500)),
                ('customer_name', models.CharField(max_length=1000)),
                ('customer_mobile', models.CharField(max_length=1000)),
                ('buying_price', models.CharField(max_length=1000)),
                ('amount', models.CharField(max_length=1000)),
                ('discount', models.CharField(max_length=1000)),
                ('total', models.CharField(max_length=1000)),
            ],
        ),
    ]
