# Generated by Django 3.1.4 on 2022-11-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_billing_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invent',
            name='qutity',
            field=models.FloatField(max_length=1000),
        ),
    ]
